apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-app-clearsessions-cronjob
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: django-clearsessions
              image: sergryap/django_app
              envFrom:
                - configMapRef:
                    name: django-app-config
              imagePullPolicy: IfNotPresent
              command: ["python", "manage.py", "clearsessions"]
          restartPolicy: OnFailure