apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app  : django-app
    env  : prod
    owner: SergRyap
spec:
  replicas: 3
  selector:
    matchLabels:
      project: k8s-django
  template:
    metadata:
      labels:
        project: k8s-django # Service will look for those PODS Labels
    spec:
      hostNetwork: true
      containers:
        - name: django-app
          image: sergryap/django_app
          envFrom:
            - configMapRef:
                name: django-app-config
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  labels:
    env  : prod
    owner: SergRyap
spec:
  selector:
    project: k8s-django    # Selecting PODS with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on NodePort
      targetPort: 80  # Port on POD
  type: NodePort

#kubectl expose deployment django-app-deployment --type=NodePort --port=80
#minikube service django-app-service --url
#kubectl create configmap django-app-config --from-env-file=backend_main_django/.env - For more flexibility and decoupling from Kubernetes, you can also use external configuration files in the format VAR=VAL